[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
seven_token = "GaQcSCxSu3iWk7C6oxPm9aBavuK5GaWJguRcbx7AFFLE"

[programs.devnet]
seven_token = "GaQcSCxSu3iWk7C6oxPm9aBavuK5GaWJguRcbx7AFFLE"

[programs.mainnet]
seven_token = "GaQcSCxSu3iWk7C6oxPm9aBavuK5GaWJguRcbx7AFFLE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"  # Setting to localnet for local testing
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "anchor deploy --program-name seven_token"
